[package]
name = "hunt-the-wumpus-rust"
version = "0.1.0"
authors = ["willbush <will.g.bush@gmail.com>"]

[dependencies]
rand = "0.7.2"

[dev-dependencies]
quickcheck = "0.9.0"
quickcheck_macros = "0.8.0"
