[package]
name = "hunt-the-wumpus-rust"
version = "0.1.0"
authors = ["willbush <will.g.bush@gmail.com>"]

[dependencies]
rand = "0.3.16"

[dev-dependencies]
quickcheck = "0.4.1"
quickcheck_macros = "0.4.2"
