# https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md

array_horizontal_layout_threshold = 60
single_line_if_else = true
single_line_if_else_max_width = 60
struct_lit_width = 30
chain_split_single_child = true
closure_block_indent_threshold = 1
condense_wildcard_suffixes = true
control_style = "Legacy"
fn_brace_style = "PreferSameLine"
fn_single_line = true
item_brace_style = "PreferSameLine"
reorder_imported = true
reorder_imported_names = true
reorder_imports_in_group = true
trailing_comma = "Never"
where_density = "Compressed"
multiline_closure_forces_block = true