# https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md

array_horizontal_layout_threshold = 60
chain_split_single_child = true
closure_block_indent_threshold = 1
condense_wildcard_suffixes = true
multiline_closure_forces_block = true
reorder_imported = true
reorder_imported_names = true
reorder_imports_in_group = true
single_line_if_else = true
single_line_if_else_max_width = 60
struct_lit_width = 40
trailing_comma = "Never"